/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author gaort
 */
public class registroAnimales extends javax.swing.JFrame {

    private int contador = 0;
    private String[] nombres = new String[100];
    private String[] especies = new String[100];
    private int[] edades = new int[100];
    private String[] habitats = new String[100];

    public registroAnimales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rInfo = new javax.swing.JButton();
        coInfo = new javax.swing.JButton();
        Regresar2 = new javax.swing.JButton();
        eAnimalestxt = new javax.swing.JTextField();
        hAnimalestxt = new javax.swing.JTextField();
        nAnimalestxt = new javax.swing.JTextField();
        edAnimalestxt = new javax.swing.JTextField();
        bInfo = new javax.swing.JButton();
        mInfo = new javax.swing.JButton();
        eInfo1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setText("Registro De Animales");

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel3.setText("Especie");

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel4.setText("Edad");

        jLabel5.setBackground(new java.awt.Color(0, 102, 102));
        jLabel5.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel5.setText("Habitat");

        rInfo.setBackground(new java.awt.Color(0, 204, 204));
        rInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rInfo.setForeground(new java.awt.Color(0, 0, 0));
        rInfo.setText("Registrar información");
        rInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rInfoActionPerformed(evt);
            }
        });

        coInfo.setBackground(new java.awt.Color(0, 204, 204));
        coInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        coInfo.setForeground(new java.awt.Color(0, 0, 0));
        coInfo.setText("Consultar información");
        coInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coInfoActionPerformed(evt);
            }
        });

        Regresar2.setBackground(new java.awt.Color(204, 0, 0));
        Regresar2.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        Regresar2.setText("Regresar");
        Regresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresar2ActionPerformed(evt);
            }
        });

        hAnimalestxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hAnimalestxtActionPerformed(evt);
            }
        });

        nAnimalestxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nAnimalestxtActionPerformed(evt);
            }
        });

        bInfo.setBackground(new java.awt.Color(0, 204, 204));
        bInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bInfo.setForeground(new java.awt.Color(0, 0, 0));
        bInfo.setText("Buscar Información");
        bInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInfoActionPerformed(evt);
            }
        });

        mInfo.setBackground(new java.awt.Color(0, 204, 204));
        mInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mInfo.setForeground(new java.awt.Color(0, 0, 0));
        mInfo.setText("Modificar Información");
        mInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mInfoActionPerformed(evt);
            }
        });

        eInfo1.setBackground(new java.awt.Color(0, 204, 204));
        eInfo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eInfo1.setForeground(new java.awt.Color(0, 0, 0));
        eInfo1.setText("Eliminar Información");
        eInfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eInfo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hAnimalestxt)
                    .addComponent(edAnimalestxt)
                    .addComponent(eAnimalestxt)
                    .addComponent(nAnimalestxt)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(rInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(267, 267, 267))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Regresar2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(mInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nAnimalestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eAnimalestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edAnimalestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hAnimalestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(Regresar2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rInfoActionPerformed
        String nombre = nAnimalestxt.getText();
        String especie = eAnimalestxt.getText();
        String edad = edAnimalestxt.getText();
        String habitat = hAnimalestxt.getText();

        if (nombre.isEmpty() || especie.isEmpty() || edad.isEmpty() || habitat.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error, completa todos los campos ");
        } else if (ent(edad) && str(nombre) && str(especie) && str(habitat)) {
            int edadInt = Integer.parseInt(edad);

            if (contador < nombres.length) {
                nombres[contador] = nombre;
                especies[contador] = especie;
                edades[contador] = edadInt;
                habitats[contador] = habitat;

                contador++;

                nAnimalestxt.setText("");
                eAnimalestxt.setText("");
                edAnimalestxt.setText("");
                hAnimalestxt.setText("");

                JOptionPane.showMessageDialog(null, "Datos guardados correctamente ");
            } else {
                JOptionPane.showMessageDialog(null, "Error, no hay espacio disponible para más animales ");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error, no se permiten los datos ingresados ");
        }
    }

    private void imprimir() {
        if (contador == 0) {
            JOptionPane.showMessageDialog(null, "No hay animales en el registro.");
        } else {
            String mensaje = "";
            for (int i = 0; i < contador; i++) {
                mensaje += "Animal " + (i + 1) + ":\n";
                mensaje += "Nombre: " + nombres[i] + "\n";
                mensaje += "Especie: " + especies[i] + "\n";
                mensaje += "Edad: " + edades[i] + "\n";
                mensaje += "Habitat: " + habitats[i] + "\n";
                mensaje += ("\n");
            }
            JOptionPane.showMessageDialog(null, mensaje);
        }
    }

    private void buscarAnimal(String nombre) {
        boolean encontrado = false;

        for (int i = 0; i < contador; i++) {
            if (nombres[i].equalsIgnoreCase(nombre)) {
                JOptionPane.showMessageDialog(null, "Animal encontrado \nNombre: " + nombres[i]
                        + "\nEspecie: " + especies[i]
                        + "\nEdad: " + edades[i]
                        + "\nHabitat: " + habitats[i]);
                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(null, "Animal no encontrado.");
        }
    }

    private void eliminarAnimal(String nombre) {
        boolean encontrado = false;

        for (int i = 0; i < contador; i++) {
            if (nombres[i].equalsIgnoreCase(nombre)) {
                for (int j = i; j < contador - 1; j++) {
                    nombres[j] = nombres[j + 1];
                    especies[j] = especies[j + 1];
                    edades[j] = edades[j + 1];
                    habitats[j] = habitats[j + 1];
                }
                contador--;
                encontrado = true;
                JOptionPane.showMessageDialog(null, "Animal eliminado correctamente.");
                break;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(null, "Animal no encontrado.");
        }
    }

    private boolean str(String valor) {
        return valor.matches("[a-zA-Z]+");
    }

    private boolean ent(String valor) {
        return valor.matches("\\d+");


    }//GEN-LAST:event_rInfoActionPerformed

    private void Regresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresar2ActionPerformed
        Ventana1 ventana = new Ventana1();

        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Regresar2ActionPerformed

    private void coInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coInfoActionPerformed

        imprimir();
    }//GEN-LAST:event_coInfoActionPerformed

    private void nAnimalestxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nAnimalestxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nAnimalestxtActionPerformed

    private void hAnimalestxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hAnimalestxtActionPerformed

    }//GEN-LAST:event_hAnimalestxtActionPerformed

    private void bInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInfoActionPerformed
        String buscar = JOptionPane.showInputDialog(null, "Ingrese el nombre del animal que quiera buscar ");
        buscarAnimal(buscar);
    }//GEN-LAST:event_bInfoActionPerformed

    private void mInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mInfoActionPerformed

        Animal animal = new Animal();
        animal.opcion();
    }//GEN-LAST:event_mInfoActionPerformed

    private void eInfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eInfo1ActionPerformed
        String eliminar = JOptionPane.showInputDialog(null, "Ingrese el nombre del animal que quiera quitar de la info ");
        eliminarAnimal(eliminar);
    }//GEN-LAST:event_eInfo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registroAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registroAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registroAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registroAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registroAnimales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Regresar2;
    private javax.swing.JButton bInfo;
    private javax.swing.JButton coInfo;
    private javax.swing.JTextField eAnimalestxt;
    private javax.swing.JButton eInfo1;
    private javax.swing.JTextField edAnimalestxt;
    private javax.swing.JTextField hAnimalestxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mInfo;
    private javax.swing.JTextField nAnimalestxt;
    private javax.swing.JButton rInfo;
    // End of variables declaration//GEN-END:variables
}
