/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author gaort
 */
public class Ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana1
     */
    public Ventana2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rAnimales = new javax.swing.JButton();
        rEvento = new javax.swing.JButton();
        rHabitats = new javax.swing.JButton();
        rAlimenticio = new javax.swing.JButton();
        Regresar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaz/zoo5.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        rAnimales.setBackground(new java.awt.Color(255, 255, 255));
        rAnimales.setForeground(new java.awt.Color(0, 0, 0));
        rAnimales.setText("Consultar Animales");
        rAnimales.setActionCommand("RegistroAnimales");
        rAnimales.setBorder(null);
        rAnimales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rAnimalesMouseEntered(evt);
            }
        });
        rAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAnimalesActionPerformed(evt);
            }
        });

        rEvento.setBackground(new java.awt.Color(255, 255, 255));
        rEvento.setForeground(new java.awt.Color(0, 0, 0));
        rEvento.setText("Consultar Eventos");
        rEvento.setActionCommand("RegistroEventos");
        rEvento.setBorder(null);
        rEvento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rEventoMouseEntered(evt);
            }
        });
        rEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rEventoActionPerformed(evt);
            }
        });

        rHabitats.setBackground(new java.awt.Color(255, 255, 255));
        rHabitats.setForeground(new java.awt.Color(0, 0, 0));
        rHabitats.setText("Consultar Habitats");
        rHabitats.setActionCommand("RegistroHabitat");
        rHabitats.setBorder(null);
        rHabitats.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rHabitats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rHabitatsMouseEntered(evt);
            }
        });
        rHabitats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rHabitatsActionPerformed(evt);
            }
        });

        rAlimenticio.setBackground(new java.awt.Color(255, 255, 255));
        rAlimenticio.setForeground(new java.awt.Color(0, 0, 0));
        rAlimenticio.setText("Consultar Alimentación");
        rAlimenticio.setActionCommand("RegistrarAlimento");
        rAlimenticio.setBorder(null);
        rAlimenticio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rAlimenticio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rAlimenticioMouseEntered(evt);
            }
        });
        rAlimenticio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAlimenticioActionPerformed(evt);
            }
        });

        Regresar1.setBackground(new java.awt.Color(255, 0, 0));
        Regresar1.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        Regresar1.setText("Regresar");
        Regresar1.setActionCommand("BotonRegresar");
        Regresar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresar1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Menú Principal");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Ver Mapa");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Consultar visitantes");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(rAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rHabitats, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rAlimenticio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Regresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(106, 106, 106)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rHabitats, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rAlimenticio, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(Regresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jLabel1.getAccessibleContext().setAccessibleParent(jLabel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rAlimenticioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rAlimenticioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_rAlimenticioMouseEntered

    private void rHabitatsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rHabitatsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_rHabitatsMouseEntered

    private void rAnimalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rAnimalesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_rAnimalesMouseEntered

    private void rEventoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rEventoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_rEventoMouseEntered

    private void Regresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresar1ActionPerformed
        Interfaz ventana = new Interfaz();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Regresar1ActionPerformed

    private void rAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAnimalesActionPerformed
        
        Animal animales = new Animal();
        
        animales.mostrarV2();
    }//GEN-LAST:event_rAnimalesActionPerformed

    private void rHabitatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rHabitatsActionPerformed
        Habitat habitat = new Habitat();
        
        habitat.mostrarV2();
        
    }//GEN-LAST:event_rHabitatsActionPerformed

    private void rEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rEventoActionPerformed
        Evento evento = new Evento();
        
        evento.mostrarV2();
    }//GEN-LAST:event_rEventoActionPerformed

    private void rAlimenticioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAlimenticioActionPerformed
        Alimetos alimento = new Alimetos();
        
        alimento.mostrarV2();
    }//GEN-LAST:event_rAlimenticioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MapaOperario mapa = new MapaOperario();

        mapa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Regresar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton rAlimenticio;
    private javax.swing.JButton rAnimales;
    private javax.swing.JButton rEvento;
    private javax.swing.JButton rHabitats;
    // End of variables declaration//GEN-END:variables
}
